CREATE TABLE wds (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `wds` CHAR(10) COMMENT 'WDS name (based on J2000 position)',
    `disc` VARCHAR(10) COMMENT 'Discoverer Code (1 to 4 letters) and Number (5)',
    `comp` VARCHAR(5) COMMENT 'Components when more than 2 (1)',
    `obs1` YEAR COMMENT '? Date of first satisfactory observation, yr',
    `obs2` YEAR COMMENT '? Date of last satisfactory observation, yr',
    `nobs` SMALLINT UNSIGNED COMMENT 'Number of Observations (up to 9999)',
    `pa1` SMALLINT COMMENT '? Position Angle at date Obs1 (2), deg',
    `pa2` SMALLINT COMMENT '? Position Angle at date Obs2 (2), deg',
    `sep1` NUMERIC(5, 1) COMMENT '? Separation at date Obs1, arcsec',
    `sep2` NUMERIC(6, 2) COMMENT '? Separation at date Obs2, arcsec',
    `mag1` NUMERIC (5, 2) COMMENT '? Magnitude of First Component',
    `mag2` NUMERIC (5, 2) COMMENT '? Magnitude of Second Component',
    `sptype` VARCHAR(10) COMMENT 'Spectral Type (Primary/Secondary)',
    `pmRA1` SMALLINT UNSIGNED COMMENT '? Primary Proper Motion (RA), mas/yr',
    `pmDE1` SMALLINT UNSIGNED COMMENT '? Primary Proper Motion (Dec), mas/yr',
    `pmRA2` SMALLINT UNSIGNED COMMENT '? Secondary Proper Motion (RA), mas/yr',
    `pmDE2` SMALLINT UNSIGNED COMMENT '? Secondary Proper Motion (Dec), mas/yr',
    `dm` CHAR(9) COMMENT 'Durchmusterung Number (3)',
    `notes` CHAR(4) COMMENT '[B-Z ] Notes about the binary (4)',
    `n_rah` CHAR(1) COMMENT '[!] indicates a position derived from WDS name',
    `rah` SMALLINT UNSIGNED COMMENT 'Right Ascension J2000 (Ep=J2000, hours)',
    `ram` SMALLINT UNSIGNED COMMENT 'Right Ascension J2000 (Ep=J2000, minutes)',
    `ras` NUMERIC(5, 2) COMMENT '[0/60] Right Ascension J2000 (Ep=J2000, seconds)',
    `de_sign` CHAR(1) COMMENT 'Declination J2000 (Ep=J2000, sign)',
    `ded` SMALLINT UNSIGNED COMMENT 'Declination J2000 (Ep=J2000, degrees)',
    `dem` SMALLINT UNSIGNED COMMENT 'Declination J2000 (Ep=J2000, minutes)',
    `des` NUMERIC(4, 1) COMMENT '[0/60]? Declination J2000 (Ep=J2000, seconds)',
    PRIMARY KEY (id),
    KEY `wds` (`wds`(4))
);
